eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
    api-b:
      path: /api-backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE
    api-c:
      path: /api-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 120000000
ribbon:
  ReadTimeout: 12000000
  ConnectTimeout: 12000000


  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 12000000
    connect-timeout-millis: 12000000