spring:
  application:
    name: index-codes-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000000
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000


  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 300000
    connect-timeout-millis: 300000